### ISSUE TITLE
Stereovision on debian 9

### ISSUE THREAD

**Issue by blup-Blupon** [erget/StereoVision#18]
Hi!

I successfully installed stereovision on Debian 9:

```
user@host:~$ pip install StereoVision
Collecting StereoVision
Installing collected packages: StereoVision
Successfully installed StereoVision-1.0.4
```
But calling functions from the command line doesn't work as expected. Did I miss something ?
```
user@host:~$ show_webcams
bash: show_webcams: command not found
```
Thanks for sharing your work through your tutorial !

**Comment by erget** [comment]
The binary `show_webcams` isn't being found - perhaps pip installed it to a directory that isn't in your search path? I'm surprised about this, since if `user` has write access to all system directories, as you command suggests, then pip should automatically place the binaries in the package in a directory that bash would find.

A workaround would be to use some kind of utility to discover where `show_webcams` was installed to, e.g. `locate`, which tells you what directory a given file is located in. After finding where it was installed, you can then add that directory to your search path.
