### ISSUE TITLE
point_cloud.py

### ISSUE THREAD

**Issue by annacesar** [erget/StereoVision#27]
I am trying to use you stereovision library to create point cloud, but I cannot get i to work.
this the command that I have written:
output = sv.point_cloud.PointCloud(points, colors)
and this is the error that I get:
module 'stereovision' has no attribute 'point_cloud'

Would you mind helping me in fixing this issue?

I am using openCV 3.3.1

**Comment by erget** [comment]
This is because `__init__.py` doesn't import the accompanying modules - you have to pull them in explicitly if you want to work with them directly, like so:

```
from stereovision.point_cloud import PointCloud
foo = PointCloud(points, colors)
```

Does that work for you?

**Comment by annacesar** [comment]
Thanks! Now the command has not given error, but I cannot find the 'foo' variable I have just created.
How can I actually export it?
What have you used to visualize the point cloud? Meshlab?

**Comment by erget** [comment]
Yes, Meshlab is my favourite for visualising point clouds. Sorry for the lack of clarity - `foo` is simply a placeholder for any variable, it's a meaningless name.

For exporting the point cloud, you can either use the command line utility `images_to_pointcloud`, which is described in greater detail [here](https://erget.wordpress.com/2014/04/27/producing-3d-point-clouds-with-a-stereo-camera-in-opencv/), or you can take a look at the sources and pull out the method that way.

I'm closing this since the original issue is solved.

**Comment by annacesar** [comment]
Hi,
I cannot locate the ply file created with:
from stereovision.point_cloud import PointCloud
foo = PointCloud(points, colors)

if I type foo in the console I get:
<stereovision.point_cloud.PointCloud at 0xea20078390>

 I have also opened your original code, but I cannot find the path in which the .ply are saved.
May you help me with this issue?

Thanks
anna
